#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Alexander Baltatzis <alba@kth.se>
"""
deploy.py — build and deploy alba-trinket to AFS.

Usage:
    python3 deploy.py

Requires deploy.cfg (copy from deploy.cfg.example and edit).
"""

import configparser
import os
import re
import shutil
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

SAVE_PHP = """\
<?php
// alba-trinket — Save endpoint for teacher mode
// Generated by deploy.py — do not edit by hand

define('SAVE_TOKEN', '{token}');

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {{
    http_response_code(405);
    echo json_encode(['error' => 'POST required']);
    exit;
}}

$SRC_ROOT = realpath(__DIR__ . '/src');
if ($SRC_ROOT === false) {{
    http_response_code(500);
    echo json_encode(['error' => 'src/ not found on server']);
    exit;
}}

$token = $_POST['token'] ?? '';
if (!hash_equals(SAVE_TOKEN, $token)) {{
    http_response_code(403);
    echo json_encode(['error' => 'Forbidden']);
    exit;
}}

$folder   = trim($_POST['folder']   ?? '');
$filename = trim($_POST['filename'] ?? '');
$content  = $_POST['content']       ?? '';

if (!preg_match('/^[a-zA-Z0-9_-]+\\.md$/', $filename)) {{
    http_response_code(400);
    echo json_encode(['error' => 'Invalid filename — must match [a-zA-Z0-9_-].md']);
    exit;
}}
if (!preg_match('/^[a-zA-Z0-9_-]+$/', $folder)) {{
    http_response_code(400);
    echo json_encode(['error' => 'Invalid folder name']);
    exit;
}}

$real_dir = realpath($SRC_ROOT . '/' . $folder);
if ($real_dir === false || strpos($real_dir . '/', $SRC_ROOT . '/') !== 0) {{
    http_response_code(400);
    echo json_encode(['error' => 'Folder not found or outside src/']);
    exit;
}}

$target = $real_dir . '/' . $filename;
if (file_put_contents($target, $content) === false) {{
    http_response_code(500);
    echo json_encode(['error' => 'Write failed — check server permissions']);
    exit;
}}

echo json_encode(['ok' => true, 'saved' => 'src/' . $folder . '/' . $filename]);
?>
"""


def load_config():
    path = os.path.join(SCRIPT_DIR, 'deploy.cfg')
    if not os.path.exists(path):
        sys.exit('Error: deploy.cfg not found — copy deploy.cfg.example and edit it.')
    cfg = configparser.ConfigParser()
    cfg.read(path)
    return cfg


def run(cmd):
    print(f'$ {cmd}')
    subprocess.run(cmd, shell=True, check=True, cwd=SCRIPT_DIR)


def update_token_in_template(token):
    path = os.path.join(SCRIPT_DIR, 'template.html')
    with open(path) as f:
        content = f.read()
    if not re.search(r"const SAVE_TOKEN = '[^']*'", content):
        print('Warning: SAVE_TOKEN not found in template.html — token not updated')
        return
    updated = re.sub(r"const SAVE_TOKEN = '[^']*'", f"const SAVE_TOKEN = '{token}'", content)
    if updated == content:
        print('Token in template.html already up to date')
    else:
        with open(path, 'w') as f:
            f.write(updated)
        print('Updated token in template.html')


def build(dist):
    src = os.path.join(SCRIPT_DIR, 'src')
    kapitel_dirs = sorted(
        d for d in os.listdir(src)
        if os.path.isdir(os.path.join(src, d))
    )
    if not kapitel_dirs:
        sys.exit('No subdirectories found in src/')
    for d in kapitel_dirs:
        run(f'python3 generate.py src/{d}/ --out {dist}/{d}/ --asset-prefix "../"')
    # Copy src/ once at top level
    src_dir = os.path.join(SCRIPT_DIR, 'src')
    dest_src = os.path.join(dist, 'src')
    if os.path.exists(dest_src):
        shutil.rmtree(dest_src)
    shutil.copytree(src_dir, dest_src, ignore=shutil.ignore_patterns('*~'))
    print(f'Copied: src/')

    for asset in ('skulpt_files', 'codemirror_files'):
        src_asset = os.path.join(SCRIPT_DIR, asset)
        dst_asset = os.path.join(dist, asset)
        if os.path.isdir(src_asset):
            if os.path.exists(dst_asset):
                shutil.rmtree(dst_asset)
            shutil.copytree(src_asset, dst_asset)
            print(f'Copied: {asset}/')

    for f in ('index.html', '.htaccess'):
        src_f = os.path.join(SCRIPT_DIR, f)
        if os.path.isfile(src_f):
            shutil.copy2(src_f, os.path.join(dist, f))
            print(f'Copied: {f}')


def main():
    cfg = load_config()
    token      = cfg['deploy']['save_token']
    ssh_host   = cfg['deploy']['ssh_host']
    remote     = cfg['deploy']['remote_path'].rstrip('/')

    dist = os.path.join(SCRIPT_DIR, 'dist')
    os.makedirs(dist, exist_ok=True)

    # 1. Update token in template.html
    update_token_in_template(token)

    # 2. Build everything into dist/
    build(dist)

    # 3. Generate save.php into dist/
    save_php_path = os.path.join(dist, 'save.php')
    with open(save_php_path, 'w') as f:
        f.write(SAVE_PHP.format(token=token))
    print(f'Generated: dist/save.php')

    # 4. rsync dist/ to remote
    run(f'rsync -avz --checksum --delete {dist}/ {ssh_host}:{remote}/')

    # 5. Set AFS permissions on src subdirs
    src_dist = os.path.join(dist, 'src')
    if os.path.isdir(src_dist):
        for d in sorted(os.listdir(src_dist)):
            if os.path.isdir(os.path.join(src_dist, d)):
                run(f'ssh {ssh_host} "fs sa {remote}/src/{d} cscwwwservice rliw"')

    print('\nDeploy complete.')


if __name__ == '__main__':
    main()
